### PR TITLE
if name doesnt exist, add field

### PR DESCRIPTION
**Pull request by NirmalMulji**
**Notes**
- if user name doesn't exist, show inputfield

**Testing**
- adding name to updates the document in firestore
- if name already exists, hide the inputfield

Screen Shot 2020-11-23 at 11 41 32 PM

Screen Shot 2020-11-23 at 11 38 33 PM

### CODE REVIEW

**Comment by sbangalore** [comment]
Nice work. I don’t think we want to show this for the owner — rather it’s for when users first sign in to view their reservations. Are these the screens we’re looking at?

Sent from my iPhone

On Nov 24, 2020, at 2:00 AM, Nirmal Mulji <notifications@github.com<mailto:notifications@github.com>> wrote:

EXTERNAL EMAIL:

Assigned #26<https://github.com/sbangalore/android-gym-project/pull/26> to @sbangalore<https://github.com/sbangalore>.

**Comment by NirmalMulji** [comment]
This screen is for a member, but it will also show up for the owner.  Even for owner, we could just leave it and the owner will just assign themselves a name.  It will only show up the first time.
I could remove it for owner if you want though, just let me know. 

Also, could you make it so the add and remove user fields don't show up for members?

**Comment by sbangalore** [comment]
Sure, that’s fine — we can keep it for the owner now, and then remove it later in refinements. Can you add an issue for having the add & remove not show up for members? I’ll start working again on the project tomorrow morning. Finishing up some parallel systems work.

On Nov 24, 2020, at 6:16 PM, Nirmal Mulji <notifications@github.com<mailto:notifications@github.com>> wrote:

EXTERNAL EMAIL:


This screen is for a member, but it will also show up for the owner. Even for owner, we could just leave it and the owner will just assign themselves a name. It will only show up the first time.
I could remove it for owner if you want though, just let me know.

Also, could you make it so the add and remove user fields don't show up for members?

**Comment by NirmalMulji** [comment]
Sure, just added the issue.  Should I go ahead and merge the commit now?

**Comment by sbangalore** [comment]
Yes, please go ahead — approved.

On Nov 24, 2020, at 7:54 PM, Nirmal Mulji <notifications@github.com<mailto:notifications@github.com>> wrote:

EXTERNAL EMAIL:


Sure, just added the issue. Should I go ahead and merge the commit now?

**Pull request merged**
