### PR TITLE
added custom users collection on sign-in

### PR DESCRIPTION
**Pull request by NirmalMulji**
**Notes**
- Added a 'users' document upon sign-in
- fixed bug where the nav-graph isnt updating.  moved the code to "onActivityResult"

**Testing**
- signing in to a user adds the corresponding document in firestore. see below
- only adds a new user once

Screen Shot 2020-11-22 at 10 53 14 PM

### CODE REVIEW

**Comment by sbangalore** [comment]
Great. Have we tested that it doesn't add them twice if they sign out and back in?

**Comment by NirmalMulji** [comment]
good catch.  I fixed it so that doesn't happen anymore

**Review by sbangalore — APPROVED** [review]
Good to go with change.

**Comment by sbangalore** [comment]
@NirmalMulji - Is there a way we can get the name of the user on sign in as well through a fragment? I'm thinking that we can use this for the chat and reservation systems.

**Comment by NirmalMulji** [comment]
The problem is that since we created the users in firebase, we never assigned them a name.  If there was one, it should show up

**Comment by sbangalore** [comment]
That makes sense. How about we create a inputview in the dashboard that shows up if the name is empty which the user sets. On setting it, the other components of the fragment become visible.

**Comment by NirmalMulji** [comment]
Ya I think thats a good idea.  I can add that tomorrow

**Pull request merged**
