### PR TITLE
Time filtering

### PR DESCRIPTION
**Pull request by NirmalMulji**
**Notes**
- filter member dashboard to only show reservations that haven't expired
- filter available timeslots to only show timeslots that haven't expired
- all timeslots, including expired ones, are still available for owner

**Testing**
- verified that filtering works - only display reservations/timeslots that are greater than the current time 

Screen Shot 2020-12-05 at 4 13 40 PM
Screen Shot 2020-12-05 at 4 13 34 PM

### CODE REVIEW

**Comment by sbangalore** [comment]
Great. Can we reduce the space in between the bottom action bar and the create fragment.

**Comment by NirmalMulji** [comment]
ya let me fix that real quick

**Comment by NirmalMulji** [comment]
added fix - removed the space

**Comment by sbangalore** [comment]
Approved.

**Review by sbangalore — APPROVED** [review]

**Pull request merged**
