### PR TITLE
add view users for owner

### PR DESCRIPTION
**Pull request by sbangalore**
**Notes**
- when owner clicks view, they can see the users signed up for a particular timeslot

**Todo**
- update design

**Testing**
- checked switching to fragments
- checked making fragment twice, etc.
- checked returns

Screen Shot 2020-12-02 at 3 28 28 AM

### CODE REVIEW

**Comment by NirmalMulji** [comment]
Did you test to see if the "users" fragment is popping correctly when you click on "dashboard", "chat", or the back button? 
Also, I see that you add "reservations" onto the backstack but I dont see it being popped anywhere.  Can you confirm that this is being handled?

**Comment by sbangalore** [comment]
Good spot. I changed that "reservations" to "users". It works fine now with the tests.

**Comment by NirmalMulji** [comment]
Good to merge after update

**Comment by sbangalore** [comment]
Let me manage that -- the commit pushed something I didn't want.

**Comment by NirmalMulji** [comment]
To get the fragment to pop correctly when pressing "back" or another fragment I had to add code in MainActivity.  I had to override the onBackPressed to pop "select" off the backstack and I had to pop when the navBar changes.  How were you able to get it working without doing this?

**Comment by sbangalore** [comment]
The fix works for the chat and doesn't work for the dashboard. I initially thought that you popped w/o respect to the tag. Let me go through this more thoroughly.

**Comment by NirmalMulji** [comment]
you can look at pull request 34 to see how I handled it.  There might be a better way im not sure though
https://github.com/sbangalore/android-gym-project/pull/34

**Pull request merged**
